export const curtain = document.getElementById('curtain')

export const subMenus = document.getElementsByClassName('menu--item')
export const menuArrow = document.getElementById('menu-arrow')
export const menuBtn = document.getElementById("menu-button")
export const menuBtnTrigger = document.getElementById("menu-button-trigger")
export const btnSendEmail = document.getElementById('btnSendEmail')

export const navBtnHome = document.getElementById('navBtnHome')
export const navBtnBlog = document.getElementById('navBtnBlog')
export const navBtnPortfolio = document.getElementById('navBtnPortfolio')
export const navBtnAbout = document.getElementById('navBtnAbout')
export const navBtnContact = document.getElementById('navBtnContact')

export const htmlCssCourseList = document.getElementById('html-css-list')
export const jsCourseList = document.getElementById('js-list')
export const pythonCourseList = document.getElementById('python-list')
export const ddbbCourseList = document.getElementById('ddbb-list')
export const otherCourseList = document.getElementById('other-list')

export const courseListHtmlAndCss = document.getElementsByClassName('html-css-course')
export const courseListJs = document.getElementsByClassName('js-course')
export const courseListPython = document.getElementsByClassName('python-course')
export const courseListDdbb = document.getElementsByClassName('ddbb-course')
export const courseListOthers = document.getElementsByClassName('other-course')

export const htmlCssList = document.getElementById('htmlCssList')
export const javascriptList = document.getElementById('javascriptList')
export const pythonList = document.getElementById('pythonList')
export const ddbbList = document.getElementById('ddbbList')
export const otherList = document.getElementById('otherList')

export const htmlAndCssArrow = document.getElementById('html-css-arrow')
export const jsArrow = document.getElementById('js-arrow')
export const pythonArrow = document.getElementById('python-arrow')
export const ddbbArrow = document.getElementById('ddbb-arrow')
export const otherArrow = document.getElementById('other-arrow')